---
language: python
python: "2.7"

addons:
  ssh_known_hosts: ssh.bgill.eu

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y ansible sshpass

script:
  - echo "$ANSIBLE_HOST" > ansible-hosts
  - ansible-playbook deploy.yaml -i ansible-hosts -vvvv
