sudo: true
language: go
dist: bionic

env:
  global:
    - HUGO_VERSION=0.73.0
    # WEBDAV_PASSWORD
    - secure: "zYa2C08awDSFcSfUv4KQvfZLh325zLM4PpmcHpChmiem0HoqT24OPytjxI9KRPTDAR1KXKCslGdtSQYZUx9gfnmUN1CvGLDE5SPCKRnYt9tJOZWS2HIUCutm9xLo0N69QvjCJv1PEI+WGZtZoxICLZg/n9EWp93ifM4Cb1I7MDOshMTuLZXP+zTOgZOiiGuvyW9W4uR+hAFRghL+RHLmwInr+o9AKFItvK4wjm2+ddSWo29YsrcRbe7RA6MVD+RLol3kVUlnq+Q/HCDDMGKUcR4W127kQuMM9LnklYfMFJhxPuml5yjGoynDwocNTlnfsIKfDi38fLMEe2ixNjRPb2qYWDxUsHc/FwFi3JCBSMdZjVWVDn0VdFbk3z+Dfs+/nLPv87kucqJ9MB8A2DP57U9ieYBN0hgqAGzhW75qITyXdeqfoQ97b2zqGW2Wz9YIGSHVPZpwCFBZTMyalNBMv9JPWv2QFm0z0l46mYO0E2228hQ6+ZMDg5xTvRGNWUyMIh7wNpz7rKF/4Fj5o+rloCqwQF7wq0i/pwkvwr8uWhJmHFVRwnESvTeqXFghZnvccc2gSkne5MHXyN/MoY5Bx8SZzgoZePOhg90w3wM5bmsBkEOORRcCyL9HNblPeW5yEzswMwvFPRoatZsfJdl402rm1QHFnWSwEsRDfl3ooFo="

before_install:
  - curl https://rclone.org/install.sh | sudo bash

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

script:
  - hugo -d www/

deploy:
  - provider: script
    script: rclone copy www fastmail:b.bjgill.net/files/website -v --webdav-pass $WEBDAV_PASSWORD --config rclone.conf
    skip_cleanup: true
    on:
      branch: master
