languageCode = "en-gb"
baseurl = "https://bjgill.github.io/"
title = "BGill"
copyright = "Benjamin Gill"
theme = "ghostwriter"
canonifyurls = true

[Author]
    name = "Benjamin Gill"

[Params]
    intro = true
    headline = "Idle chatter of a transcendental kind"
    description = "Benjamin Gill's website"
    github = "https://github.com/bjgill"
    email = "website@bgill.eu"
    opengraph = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4

[[menu.main]]
    name = "Links"
    url = "/page/links/"
    weight = 5
